(() => {
  "use strict";

  const snapshotDate = "2026-07-29";

  window.DIALYSIS_TRANSIT_SAMPLE_DATA = {
    metadata: {
      mode: "demonstration",
      fixtureVersion: "1.0.0",
      preparedAt: snapshotDate,
      facilitySource: "Synthetic CMS-shaped demonstration fixtures",
      transitSource: "Synthetic BTS-shaped demonstration fixtures",
      geocoderSource: "Synthetic Census-shaped geocoding fixtures",
      notice:
        "Demonstration records are fictional and exist only to exercise the Phase 1 interface.",
    },
    facilities: [
      {
        ccn: "990001",
        name: "Tucson Central Dialysis — demonstration",
        address: "101 W Congress St",
        city: "Tucson",
        state: "AZ",
        zip: "85701",
        county: "Pima",
        telephone: "(520) 555-0101",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Desert Kidney Network",
        lateShift: "Yes",
        stations: 24,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2014-06-18",
        lat: 32.2226,
        lng: -110.9747,
        geocodeStatus: "exact",
        matchedAddress: "101 W Congress St, Tucson, AZ 85701",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990002",
        name: "South Tucson Renal Center — demonstration",
        address: "2401 S 6th Ave",
        city: "Tucson",
        state: "AZ",
        zip: "85713",
        county: "Pima",
        telephone: "(520) 555-0102",
        ownership: "Non-profit",
        chainOwned: "No",
        chain: "Independent",
        lateShift: "No",
        stations: 18,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: false,
        certificationDate: "2017-02-09",
        lat: 32.1967,
        lng: -110.9687,
        geocodeStatus: "manual_override",
        matchedAddress: "2401 S 6th Ave, Tucson, AZ 85713",
        geocodeBenchmark: "Verified fixture override",
        geocodeSource: "manual_override",
        snapshotDate,
      },
      {
        ccn: "990003",
        name: "Flagstaff Mountain Dialysis — demonstration",
        address: "150 N San Francisco St",
        city: "Flagstaff",
        state: "AZ",
        zip: "86001",
        county: "Coconino",
        telephone: "(928) 555-0103",
        ownership: "Government/other",
        chainOwned: "No",
        chain: "High Country Health",
        lateShift: "Unknown",
        stations: 12,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: false,
        certificationDate: "2019-08-21",
        lat: 35.1983,
        lng: -111.6513,
        geocodeStatus: "non_exact",
        matchedAddress: "100 block N San Francisco St, Flagstaff, AZ 86001",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990004",
        name: "Mesa East Dialysis — demonstration",
        address: "5000 E Main St",
        city: "Mesa",
        state: "AZ",
        zip: "85205",
        county: "Maricopa",
        telephone: "(480) 555-0104",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Desert Kidney Network",
        lateShift: "No",
        stations: 20,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: false,
        certificationDate: "2021-04-14",
        lat: null,
        lng: null,
        geocodeStatus: "no_match",
        matchedAddress: "",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990101",
        name: "Los Angeles Civic Dialysis — demonstration",
        address: "200 N Spring St",
        city: "Los Angeles",
        state: "CA",
        zip: "90012",
        county: "Los Angeles",
        telephone: "(213) 555-0101",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Pacific Renal Partners",
        lateShift: "Yes",
        stations: 32,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2011-10-04",
        lat: 34.0522,
        lng: -118.2437,
        geocodeStatus: "exact",
        matchedAddress: "200 N Spring St, Los Angeles, CA 90012",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990102",
        name: "Fresno Valley Kidney Center — demonstration",
        address: "2600 Fresno St",
        city: "Fresno",
        state: "CA",
        zip: "93721",
        county: "Fresno",
        telephone: "(559) 555-0102",
        ownership: "Non-profit",
        chainOwned: "No",
        chain: "Central Valley Health",
        lateShift: "No",
        stations: 21,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: false,
        certificationDate: "2016-05-12",
        lat: 36.7378,
        lng: -119.7871,
        geocodeStatus: "exact",
        matchedAddress: "2600 Fresno St, Fresno, CA 93721",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990103",
        name: "Sacramento River Dialysis — demonstration",
        address: "Unresolved fixture address",
        city: "Sacramento",
        state: "CA",
        zip: "95814",
        county: "Sacramento",
        telephone: "(916) 555-0103",
        ownership: "Government/other",
        chainOwned: "No",
        chain: "Independent",
        lateShift: "Unknown",
        stations: 10,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: false,
        certificationDate: "2022-01-10",
        lat: null,
        lng: null,
        geocodeStatus: "tie",
        matchedAddress: "",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990201",
        name: "Denver Union Dialysis — demonstration",
        address: "1701 Wynkoop St",
        city: "Denver",
        state: "CO",
        zip: "80202",
        county: "Denver",
        telephone: "(303) 555-0201",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Front Range Renal",
        lateShift: "Yes",
        stations: 28,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2013-03-08",
        lat: 39.7392,
        lng: -104.9903,
        geocodeStatus: "exact",
        matchedAddress: "1701 Wynkoop St, Denver, CO 80202",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990202",
        name: "Pueblo Community Dialysis — demonstration",
        address: "301 N Main St",
        city: "Pueblo",
        state: "CO",
        zip: "81003",
        county: "Pueblo",
        telephone: "(719) 555-0202",
        ownership: "Non-profit",
        chainOwned: "No",
        chain: "Southern Colorado Care",
        lateShift: "No",
        stations: 14,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: false,
        certificationDate: "2018-11-30",
        lat: 38.2544,
        lng: -104.6091,
        geocodeStatus: "non_exact",
        matchedAddress: "300 block N Main St, Pueblo, CO 81003",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990301",
        name: "Miami Bay Dialysis — demonstration",
        address: "100 SE 2nd St",
        city: "Miami",
        state: "FL",
        zip: "33131",
        county: "Miami-Dade",
        telephone: "(305) 555-0301",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Suncoast Dialysis Group",
        lateShift: "Yes",
        stations: 30,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2012-07-16",
        lat: 25.7617,
        lng: -80.1918,
        geocodeStatus: "exact",
        matchedAddress: "100 SE 2nd St, Miami, FL 33131",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990302",
        name: "Tallahassee Capital Dialysis — demonstration",
        address: "300 S Adams St",
        city: "Tallahassee",
        state: "FL",
        zip: "32301",
        county: "Leon",
        telephone: "(850) 555-0302",
        ownership: "Government/other",
        chainOwned: "No",
        chain: "Capital Regional Health",
        lateShift: "Unknown",
        stations: 16,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: true,
        certificationDate: "2020-09-03",
        lat: 30.4383,
        lng: -84.2807,
        geocodeStatus: "manual_override",
        matchedAddress: "300 S Adams St, Tallahassee, FL 32301",
        geocodeBenchmark: "Verified fixture override",
        geocodeSource: "manual_override",
        snapshotDate,
      },
      {
        ccn: "990401",
        name: "Chicago Loop Dialysis — demonstration",
        address: "121 N LaSalle St",
        city: "Chicago",
        state: "IL",
        zip: "60602",
        county: "Cook",
        telephone: "(312) 555-0401",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Great Lakes Renal",
        lateShift: "Yes",
        stations: 36,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2010-12-01",
        lat: 41.8781,
        lng: -87.6298,
        geocodeStatus: "exact",
        matchedAddress: "121 N LaSalle St, Chicago, IL 60602",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990402",
        name: "Springfield Prairie Dialysis — demonstration",
        address: "300 S 7th St",
        city: "Springfield",
        state: "IL",
        zip: "62701",
        county: "Sangamon",
        telephone: "(217) 555-0402",
        ownership: "Non-profit",
        chainOwned: "No",
        chain: "Prairie Community Health",
        lateShift: "No",
        stations: 15,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: false,
        certificationDate: "2015-04-22",
        lat: 39.7817,
        lng: -89.6501,
        geocodeStatus: "non_exact",
        matchedAddress: "300 block S 7th St, Springfield, IL 62701",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990501",
        name: "Lower Manhattan Dialysis — demonstration",
        address: "1 Centre St",
        city: "New York",
        state: "NY",
        zip: "10007",
        county: "New York",
        telephone: "(212) 555-0501",
        ownership: "Non-profit",
        chainOwned: "Yes",
        chain: "Empire Kidney Alliance",
        lateShift: "Yes",
        stations: 40,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2009-05-19",
        lat: 40.7128,
        lng: -74.006,
        geocodeStatus: "exact",
        matchedAddress: "1 Centre St, New York, NY 10007",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990502",
        name: "Buffalo Lake Dialysis — demonstration",
        address: "65 Niagara Sq",
        city: "Buffalo",
        state: "NY",
        zip: "14202",
        county: "Erie",
        telephone: "(716) 555-0502",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Empire Kidney Alliance",
        lateShift: "No",
        stations: 22,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: false,
        certificationDate: "2018-02-14",
        lat: 42.8864,
        lng: -78.8784,
        geocodeStatus: "exact",
        matchedAddress: "65 Niagara Sq, Buffalo, NY 14202",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990601",
        name: "Austin Central Dialysis — demonstration",
        address: "301 W 2nd St",
        city: "Austin",
        state: "TX",
        zip: "78701",
        county: "Travis",
        telephone: "(512) 555-0601",
        ownership: "For-profit",
        chainOwned: "Yes",
        chain: "Lone Star Renal",
        lateShift: "Yes",
        stations: 27,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: true,
        certificationDate: "2014-09-25",
        lat: 30.2672,
        lng: -97.7431,
        geocodeStatus: "exact",
        matchedAddress: "301 W 2nd St, Austin, TX 78701",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
      {
        ccn: "990602",
        name: "El Paso Franklin Dialysis — demonstration",
        address: "300 N Campbell St",
        city: "El Paso",
        state: "TX",
        zip: "79901",
        county: "El Paso",
        telephone: "(915) 555-0602",
        ownership: "Government/other",
        chainOwned: "No",
        chain: "Border Health Cooperative",
        lateShift: "Unknown",
        stations: 13,
        inCenterHd: true,
        peritonealDialysis: false,
        homeHdTraining: false,
        certificationDate: "2020-01-28",
        lat: 31.7619,
        lng: -106.485,
        geocodeStatus: "manual_override",
        matchedAddress: "300 N Campbell St, El Paso, TX 79901",
        geocodeBenchmark: "Verified fixture override",
        geocodeSource: "manual_override",
        snapshotDate,
      },
      {
        ccn: "990603",
        name: "Houston Bayou Dialysis — demonstration",
        address: "901 Bagby St",
        city: "Houston",
        state: "TX",
        zip: "77002",
        county: "Harris",
        telephone: "(713) 555-0603",
        ownership: "Non-profit",
        chainOwned: "Yes",
        chain: "Lone Star Renal",
        lateShift: "No",
        stations: 25,
        inCenterHd: true,
        peritonealDialysis: true,
        homeHdTraining: false,
        certificationDate: "2016-06-07",
        lat: 29.7604,
        lng: -95.3698,
        geocodeStatus: "exact",
        matchedAddress: "901 Bagby St, Houston, TX 77002",
        geocodeBenchmark: "Public_AR_Current",
        geocodeSource: "census_fixture",
        snapshotDate,
      },
    ],
    stops: [
      {
        id: "AZ-TUC-001",
        sourceObjectId: 10001,
        stopId: "TUC-001",
        name: "Congress / Church — demonstration",
        lat: 32.2234,
        lng: -110.975,
        state: "AZ",
        type: "Bus stop",
        agency: "Sun Transit Fixture",
        ntdId: "AZ-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "AZ-TUC-002",
        sourceObjectId: 10002,
        stopId: "TUC-002",
        name: "6th Avenue / 25th Street — demonstration",
        lat: 32.2002,
        lng: -110.9687,
        state: "AZ",
        type: "Bus stop",
        agency: "Sun Transit Fixture",
        ntdId: "AZ-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "AZ-TUC-003",
        sourceObjectId: 10003,
        stopId: "TUC-003",
        name: "Downtown Transit Center — demonstration",
        lat: 32.221,
        lng: -110.9709,
        state: "AZ",
        type: "Transit center",
        agency: "Sun Transit Fixture",
        ntdId: "AZ-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "AZ-FLG-001",
        sourceObjectId: 10004,
        stopId: "FLG-001",
        name: "Mountain Line North — demonstration",
        lat: 35.21,
        lng: -111.6513,
        state: "AZ",
        type: "Bus stop",
        agency: "Mountain Transit Fixture",
        ntdId: "AZ-FIX-2",
        wheelchair: "Indicated not accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "CA-LAX-001",
        sourceObjectId: 10101,
        stopId: "LAX-001",
        name: "Civic Center Station — demonstration",
        lat: 34.0535,
        lng: -118.2437,
        state: "CA",
        type: "Rail station",
        agency: "Los Angeles Transit Fixture",
        ntdId: "CA-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "CA-LAX-002",
        sourceObjectId: 10102,
        stopId: "LAX-002",
        name: "Spring / Temple — demonstration",
        lat: 34.0556,
        lng: -118.242,
        state: "CA",
        type: "Bus stop",
        agency: "Los Angeles Transit Fixture",
        ntdId: "CA-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "CA-FAT-001",
        sourceObjectId: 10103,
        stopId: "FAT-001",
        name: "Fresno Street North — demonstration",
        lat: 36.7448,
        lng: -119.7871,
        state: "CA",
        type: "Bus stop",
        agency: "Central Valley Transit Fixture",
        ntdId: "CA-FIX-2",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "CO-DEN-001",
        sourceObjectId: 10201,
        stopId: "DEN-001",
        name: "Union Station South — demonstration",
        lat: 39.7422,
        lng: -104.9903,
        state: "CO",
        type: "Rail station",
        agency: "Front Range Transit Fixture",
        ntdId: "CO-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "CO-DEN-002",
        sourceObjectId: 10202,
        stopId: "DEN-002",
        name: "Wynkoop / 17th — demonstration",
        lat: 39.7401,
        lng: -104.996,
        state: "CO",
        type: "Bus stop",
        agency: "Front Range Transit Fixture",
        ntdId: "CO-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "CO-PUB-001",
        sourceObjectId: 10203,
        stopId: "PUB-001",
        name: "Pueblo North Terminal — demonstration",
        lat: 38.273,
        lng: -104.6091,
        state: "CO",
        type: "Transit center",
        agency: "Pueblo Transit Fixture",
        ntdId: "CO-FIX-2",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "FL-MIA-001",
        sourceObjectId: 10301,
        stopId: "MIA-001",
        name: "Bayfront North — demonstration",
        lat: 25.7623,
        lng: -80.1918,
        state: "FL",
        type: "Rail station",
        agency: "Miami Transit Fixture",
        ntdId: "FL-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "FL-MIA-002",
        sourceObjectId: 10302,
        stopId: "MIA-002",
        name: "SE 2nd / 1st Avenue — demonstration",
        lat: 25.763,
        lng: -80.1945,
        state: "FL",
        type: "Bus stop",
        agency: "Miami Transit Fixture",
        ntdId: "FL-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "FL-TLH-001",
        sourceObjectId: 10303,
        stopId: "TLH-001",
        name: "Capital North — demonstration",
        lat: 30.447,
        lng: -84.2807,
        state: "FL",
        type: "Bus stop",
        agency: "Capital Transit Fixture",
        ntdId: "FL-FIX-2",
        wheelchair: "Indicated not accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "IL-CHI-001",
        sourceObjectId: 10401,
        stopId: "CHI-001",
        name: "Clark / Lake — demonstration",
        lat: 41.8798,
        lng: -87.6298,
        state: "IL",
        type: "Rail station",
        agency: "Chicago Transit Fixture",
        ntdId: "IL-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "IL-CHI-002",
        sourceObjectId: 10402,
        stopId: "CHI-002",
        name: "LaSalle / Randolph — demonstration",
        lat: 41.883,
        lng: -87.632,
        state: "IL",
        type: "Bus stop",
        agency: "Chicago Transit Fixture",
        ntdId: "IL-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "IL-SPI-001",
        sourceObjectId: 10403,
        stopId: "SPI-001",
        name: "Springfield North — demonstration",
        lat: 39.79,
        lng: -89.6501,
        state: "IL",
        type: "Bus stop",
        agency: "Prairie Transit Fixture",
        ntdId: "IL-FIX-2",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "NY-NYC-001",
        sourceObjectId: 10501,
        stopId: "NYC-001",
        name: "City Hall Station — demonstration",
        lat: 40.7132,
        lng: -74.006,
        state: "NY",
        type: "Rail station",
        agency: "New York Transit Fixture",
        ntdId: "NY-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "NY-NYC-002",
        sourceObjectId: 10502,
        stopId: "NYC-002",
        name: "Centre / Chambers — demonstration",
        lat: 40.7147,
        lng: -74.0035,
        state: "NY",
        type: "Bus stop",
        agency: "New York Transit Fixture",
        ntdId: "NY-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "NY-BUF-001",
        sourceObjectId: 10503,
        stopId: "BUF-001",
        name: "Buffalo North — demonstration",
        lat: 42.901,
        lng: -78.8784,
        state: "NY",
        type: "Bus stop",
        agency: "Erie Transit Fixture",
        ntdId: "NY-FIX-2",
        wheelchair: "Indicated not accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "TX-AUS-001",
        sourceObjectId: 10601,
        stopId: "AUS-001",
        name: "Republic Square — demonstration",
        lat: 30.2696,
        lng: -97.7431,
        state: "TX",
        type: "Transit center",
        agency: "Austin Transit Fixture",
        ntdId: "TX-FIX-1",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "TX-AUS-002",
        sourceObjectId: 10602,
        stopId: "AUS-002",
        name: "2nd / Guadalupe — demonstration",
        lat: 30.2655,
        lng: -97.746,
        state: "TX",
        type: "Bus stop",
        agency: "Austin Transit Fixture",
        ntdId: "TX-FIX-1",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "TX-ELP-001",
        sourceObjectId: 10603,
        stopId: "ELP-001",
        name: "Franklin North — demonstration",
        lat: 31.79,
        lng: -106.485,
        state: "TX",
        type: "Bus stop",
        agency: "El Paso Transit Fixture",
        ntdId: "TX-FIX-2",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "TX-HOU-001",
        sourceObjectId: 10604,
        stopId: "HOU-001",
        name: "Bagby / Walker — demonstration",
        lat: 29.765,
        lng: -95.3698,
        state: "TX",
        type: "Bus stop",
        agency: "Houston Transit Fixture",
        ntdId: "TX-FIX-3",
        wheelchair: "Indicated accessible",
        stopUrl: "",
        snapshotDate,
      },
      {
        id: "TX-HOU-002",
        sourceObjectId: 10605,
        stopId: "HOU-002",
        name: "Theater District Station — demonstration",
        lat: 29.763,
        lng: -95.366,
        state: "TX",
        type: "Rail station",
        agency: "Houston Transit Fixture",
        ntdId: "TX-FIX-3",
        wheelchair: "Unknown",
        stopUrl: "",
        snapshotDate,
      },
    ],
  };
})();
